title: File

fields:
  alt:
    label: Alt Text
    type: text
    width: 1/3
    help: >
      Helps screen-reading tools describe images to visually impaired readers and allows search engines to better crawl and rank your site.
  caption:
    label: Caption
    type: textarea
    width: 1/3
    help: >
      A caption for the image, displayed below it.
  credits:
    label: Credits
    type: textarea
    width: 1/3
    help: >
      The name of the photographer or artist.