title: Block Settings
icon: cog

fields:

  headline:
    type: headline
    label: Set colors, padding, and width.
    help: Visit the _Global Settings_ tab in the panel to review your site's color palette.

  background:
    width: 1/2
    label: Background Color
    type: select
    empty: false
    options:
      background-1: Background 1
      background-2: Background 2
      background-3: Background 3
      light: Foreground Light
      dark: Foreground Dark
      accent-1: Accent 1
      accent-2: Accent 2
      accent-3: Accent 3
      accent-4: Accent 4
    default: background-1

  foreground:
    width: 1/2
    label: Foreground Color
    type: select
    empty: false
    options:
      background-1: Background 1
      background-2: Background 2
      background-3: Background 3
      light: Foreground Light
      dark: Foreground Dark
      accent-1: Accent 1
      accent-2: Accent 2
      accent-3: Accent 3
      accent-4: Accent 4
    default: dark
  
  padding_top:
    width: 1/3
    label: Padding Top
    type: number
    after: rem
    min: 0
    max: 25
    step: 0.5
    default: 4
  
  padding_bottom:
    width: 1/3
    label: Padding Bottom
    type: number
    after: rem
    min: 0.0
    max: 25.0
    step: 0.5
    default: 4.0
  
  wrapper:
    width: 1/3
    label: Wrapper
    type: select
    empty: false
    options:
      fullscreen: Full Screen
      page-width: Page Width
      wide: Wide
      narrow: Narrow
    default: page-width

  hot_tip:
    label: What are "rems"?
    type: info
    text: >
      A "rem" is a unit of measurement that is **relative to the base font size** in your site's _Global Settings_ tab. This means that if you change the base font size of your site, the padding will change proportionally. This is a good thing! :) It means that your site will be more accessible to people with visual impairments, and it means that you can change the font size of your site without having to adjust the padding of every block.
      <br><br>
      On this site, 1rem = `{{ site.base_size }}`px. To convert rems to pixels, multiply the number of rems by `{{ site.base_size }}`. For example, 4rem = 64px.