title: Block Settings
icon: cog

fields:
  background:
    label: Background Color
    type: select
    options: query
    query: site.getBrandPalette
  foreground:
    label: Foreground Color
    type: select
    options: query
    query: site.getBrandPalette
  padding_top:
    label: Padding Top
    type: number
    after: rem
    min: 0
    max: 25
    step: 0.5
    default: 4
  padding_bottom:
    label: Padding Bottom
    type: number
    after: rem
    min: 0.0
    max: 25.0
    step: 0.5
    default: 4.0
  wrapper:
    label: Wrapper
    type: select
    options:
      fullscreen: Full Screen
      page-width: Page Width
      wide: Wide
      narrow: Narrow
    default: page-width