title: Block Settings
icon: cog

fields:
  background:
    label: Background Color
    type: select
    options:
      background-1: Background 1
      background-2: Background 2
      background-3: Background 3
      light: Foreground Light
      dark: Foreground Dark
      accent-1: Accent 1
      accent-2: Accent 2
      accent-3: Accent 3
      accent-4: Accent 4
    default: background-1
  foreground:
    label: Foreground Color
    type: select
    options:
      background-1: Background 1
      background-2: Background 2
      background-3: Background 3
      light: Foreground Light
      dark: Foreground Dark
      accent-1: Accent 1
      accent-2: Accent 2
      accent-3: Accent 3
      accent-4: Accent 4
    default: dark
  padding_top:
    label: Padding Top
    type: number
    after: rem
    min: 0
    max: 25
    step: 0.5
    default: 4
  padding_bottom:
    label: Padding Bottom
    type: number
    after: rem
    min: 0.0
    max: 25.0
    step: 0.5
    default: 4.0
  wrapper:
    label: Wrapper
    type: select
    options:
      fullscreen: Full Screen
      page-width: Page Width
      wide: Wide
      narrow: Narrow
    default: page-width