title: Block Settings
icon: cog

fields:

  headline:
    type: headline
    label: Set colors, padding, and width.
    help: Visit the _Global Settings_ tab in the panel to review your site's color palette.

  background:
    width: 1/2
    label: Background Color
    type: select
    options:
      background-1: Background 1
      background-2: Background 2
      background-3: Background 3
      light: Foreground Light
      dark: Foreground Dark
      accent-1: Accent 1
      accent-2: Accent 2
      accent-3: Accent 3
      accent-4: Accent 4
    default: background-1

  foreground:
    width: 1/2
    label: Foreground Color
    type: select
    options:
      background-1: Background 1
      background-2: Background 2
      background-3: Background 3
      light: Foreground Light
      dark: Foreground Dark
      accent-1: Accent 1
      accent-2: Accent 2
      accent-3: Accent 3
      accent-4: Accent 4
    default: dark
  
  padding_top:
    width: 1/3
    label: Padding Top
    type: number
    after: rem
    min: 0
    max: 25
    step: 0.5
    default: 4
  
  padding_bottom:
    width: 1/3
    label: Padding Bottom
    type: number
    after: rem
    min: 0.0
    max: 25.0
    step: 0.5
    default: 4.0
  
  wrapper:
    width: 1/3
    label: Wrapper
    type: select
    options:
      fullscreen: Full Screen
      page-width: Page Width
      wide: Wide
      narrow: Narrow
    default: page-width