title: Company Information

columns:
  contact:
    width: 1/2
    sections:
      contact_main:
        type: fields
        fields:
          contact_header:
            label: Contact
            type: headline

          company_name:
            label: Company Name
            type: text
          address_line_1:
            label: Address Line 1
            type: text
          address_line_2:
            label: Address Line 2
            type: text
          city:
            label: City
            type: text
            width: 1/3
          state:
            label: State
            type: select
            width: 1/3
            options:
              AL: Alabama
              AK: Alaska
              AZ: Arizona
              AR: Arkansas
              CA: California
              CO: Colorado
              CT: Connecticut
              DE: Delaware
              DC: District of Columbia
              FL: Florida
              GA: Georgia
              HI: Hawaii
              ID: Idaho
              IL: Illinois
              IN: Indiana
              IA: Iowa
              KS: Kansas
              KY: Kentucky
              LA: Louisiana
              ME: Maine
              MD: Maryland
              MA: Massachusetts
              MI: Michigan
              MN: Minnesota
              MS: Mississippi
              MO: Missouri
              MT: Montana
              NE: Nebraska
              NV: Nevada
              NH: New Hampshire
              NJ: New Jersey
              NM: New Mexico
              NY: New York
              NC: North Carolina
              ND: North Dakota
              OH: Ohio
              OK: Oklahoma
              OR: Oregon
              PA: Pennsylvania
              PR: Puerto Rico
              RI: Rhode Island
              SC: South Carolina
              SD: South Dakota
              TN: Tennessee
              TX: Texas
              UT: Utah
              VT: Vermont
              VA: Virginia
              WA: Washington
              WV: West Virginia
              WI: Wisconsin
              WY: Wyoming
          zip:
            label: Zip Code
            type: text
            width: 1/3
          email:
            label: Email Address
            type: email
            width: 1/2
            validate:
              email: true
          phone:
            label: Phone Number
            type: tel
            width: 1/2
            validate:
              phone: true
          include_fax:
            label: Add a Fax Number?
            type: toggle
            width: 1/3
            default: no
            text:
              - "no"
              - "yes"
          fax:
            label: Fax Number
            type: tel
            width: 2/3
            validate:
              phone: true
            when:
              include_fax: true
          wow:
            label: Dear Analog Afficionado,
            type: info
            theme: positive
            text: |
              You still have a fax machine?! You're the coolest.

              xoxo,
              Your friends at The Rare Beast
            when:
              include_fax: true
  social:
    width: 1/2
    sections:
      social_main:
        type: fields
        fields:
          social_header:
            label: Social
            type: headline

          instagram:
            label: Instagram
            type: url
            width: 1/2
          facebook:
            label: Facebook
            type: url
            width: 1/2
          twitter:
            label: Twitter
            type: url
            width: 1/2
          linkedin:
            label: LinkedIn
            type: url
            width: 1/2
          tiktok:
            label: TikTok
            type: url
            width: 1/2
          are.na:
            label: Are.na
            type: url
            width: 1/2
          youtube:
            label: YouTube
            type: url
            width: 1/2
          vimeo:
            label: Vimeo
            type: url
            width: 1/2
          pinterest:
            label: Pinterest
            type: url
            width: 1/2
          reddit:
            label: Reddit
            type: url
            width: 1/2