title: Hero Settings
icon: cog

fields:

  headline_a:
    type: headline
    label: Design your hero.

  height:
    width: 1/3
    label: Viewport Height
    type: select
    empty: false
    options:
      unset: Auto
      landscape: Landscape (16:9)
      half: Half Window
      three-quarters: Three-Quarters Window
      full: Full Window
    default: full
  
  foreground:
    width: 1/3
    label: Foreground Color
    type: select
    empty: false
    options:
      background-1: Background 1
      background-2: Background 2
      background-3: Background 3
      light: Foreground Light
      dark: Foreground Dark
      accent-1: Accent 1
      accent-2: Accent 2
      accent-3: Accent 3
      accent-4: Accent 4
    default: dark

  max_width:
    width: 1/3
    label: Max Width
    type: range
    min: 25
    max: 100
    default: 50
    step: 1
    after: rem

  justify_content:
    width: 1/3
    label: Horizontal Content Position
    type: select
    empty: false
    options:
      flex-start: Left
      center: Center
      flex-end: Right
    default: center
    help: |
      Position the content along the Hero block's **x-axis** (left to right).

  align_y:
    width: 1/3
    label: Vertical Content Position
    type: select
    empty: false
    options:
      top: Top
      center: Center
      bottom: Bottom
    default: center
    help: |
      Position the content along the Hero block's **y-axis** (top to bottom).

  text_align:
    width: 1/3
    label: Text Alignment
    type: select
    empty: false
    options:
      left: Left
      center: Center
      right: Right
    default: center
    help: |
      Choose your text alignment. _**Hint:** right-aligned text is probably the wrong choice._


  line_a:
    type: line

  headline_b:
    type: headline
    label: Fix contrast issues (optional).
    help: |
      These settings come in handy when you run into **contrast issues** between your content and the background image/video. Fixing contrast issues is another win for accessibility!

  content_background:
    width: 1/2
    label: Content Background
    type: color
    alpha: true
    default: "Transparent"
    mode: picker
    options:
      "ffffff00": "Transparent"
      "#f7f5e8": "Drywall"
      "#232220": "Asphalt"
      "#d3d3d3": "Concrete"
      "#e8d722": "Highlighter"
      "#3a8e0f": "Grass"
      "#ef0f00": "Poppy"
      "#434cf9": "Pond"
    help: |
      _**Hint:** just leave this transparent if you don't want to add a background color to your content._

  content_padding:
    width: 1/2
    label: Content Padding
    type: range
    min: 1
    max: 8
    default: 2
    step: 0.25
    after: rem
    help: |
      Raising this value will increase the size of the colored background behind your content cluster.

  include_overlay:
    width: 1/2
    label: Include Image/Video Overlay?
    type: toggle
    default: false
    text:
      - "No"
      - "Yes"

  image_overlay:
    width: 1/2
    label: Image/Video Overlay
    type: color
    alpha: true
    default: "Transparent"
    mode: picker
    options:
      "ffffff00": "Transparent"
      "#f7f5e8": "Drywall"
      "#232220": "Asphalt"
      "#d3d3d3": "Concrete"
      "#e8d722": "Highlighter"
      "#3a8e0f": "Grass"
      "#ef0f00": "Poppy"
      "#434cf9": "Pond"
    when:
      include_overlay: true