title: Hero Slider Settings
icon: cog

fields:

  headline_a:
    type: headline
    label: Choose pagination style.
    help: |
      These settings will only come into play when you add more than one image or video background to your Hero block.

  pagination_style:
    label: Pagination Style
    type: radio
    default: bullets
    columns: 3
    options:
      bullets: Bullets
      fraction: Fraction
      progressbar: Progress Bar

  line_a:
    type: line

  headline_b:
    type: headline
    label: Select autoplay parameters.

  autoplay:
    width: 1/2
    label: Autoplay
    type: toggle
    default: true
    text: Enable
    help: Enable autoplay?

  slide_interval:
    width: 1/2
    label: Slide Interval
    type: range
    default: 4000
    min: 1000
    max: 10000
    step: 250
    after: ms
    help: Set the amount of time each slide is visible before transitioning to the next slide.
    when:
      autoplay: true

  line_b:
    type: line

  headline_c:
    type: headline
    label: Customize slider for mobile devices.
  
  mobile_pagination:
    width: 1/2
    label: Pagination
    type: toggle
    default: true
    text: Show
    help: Show pagination on mobile?

  mobile_navigation:
    width: 1/2
    label: Navigation
    type: toggle
    default: false
    text: Show
    help: Show navigation arrows on mobile?

  mobile_slides_per_view:
    width: 1/2
    label: Slides Per View
    type: range
    default: 1
    min: 1
    max: 4
    help: How many slides should be visible at once on mobile?
  
  mobile_space_between:
    width: 1/2
    label: Space Between
    type: range
    default: 0
    min: 0
    max: 64
    after: px
    help: Set the gap between each slide on mobile.

  line_c:
    type: line

  headline_d:
    type: headline
    label: Customize slider for larger screen sizes (laptops, desktops).

  desktop_pagination:
    width: 1/2
    label: Pagination
    type: toggle
    default: true
    text: Show
    help: Show pagination on desktop?

  desktop_navigation:
    width: 1/2
    label: Navigation
    type: toggle
    default: true
    text: Show
    help: Show navigation arrows on desktop?

  desktop_slides_per_view:
    width: 1/2
    label: Slides Per View
    type: range
    default: 1
    min: 1
    max: 4
    help: How many slides should be visible at once on desktop?
  
  desktop_space_between:
    width: 1/2
    label: Space Between
    type: range
    default: 0
    min: 0
    max: 64
    after: px
    help: Set the gap between each slide on desktop.