title: Media & Content Settings
icon: cog

fields:

  headline_a:
    type: headline
    label: Adjust your content's layout.

  align_content:
    width: 1/3
    label: Align Content
    type: radio
    default: top
    options:
      top: Top
      center: Center
      bottom: Bottom

  gap:
    width: 1/3
    label: Gap
    type: range
    default: 2
    min: 0
    max: 8
    after: rem
    help: Set the gap between your media and content.

  ratio:
    width: 1/3
    label: Ratio
    type: select
    default: auto
    empty: false
    options:
      auto: Auto
      square: 1:1
      two-three: 2:3
      three-two: 3:2
      three-four: 3:4
      four-three: 4:3
      four-five: 4:5
      five-four: 5:4
      sixteen-nine: 16:9
    help: This sets the aspect ratio of your image or video. Select "Auto" to avoid cropping.

  headline_b:
    type: headline
    label: Customize your layout for mobile and desktop views.
  
  layout_mobile:
    width: 1/2
    type: radio
    label: Mobile Layout
    options:
      content-first: Content Top
      content-second: Content Bottom
    default: content-first
  
  layout_desktop:
    width: 1/2
    type: radio
    label: Desktop Layout
    options:
      content-first: Content Left
      content-second: Content Right
    default: content-first

  headline_c:
    type: headline
    label: Set the width of your media.
    help: This applies to desktop views only. Media will always be as wide as the rest of the block on mobile.

  media_width:
    type: radio
    label: Media Width
    options:
      default: Default (50%)
      two-thirds: Two-Thirds (66%)
      three-quarters: Three-Quarters (75%)
    columns: 3