title: Media Settings
icon: cog

fields:

  headline:
    type: headline
    label: Fine-tune your layout.

  alignment:
    width: 1/2
    label: Alignment
    type: radio
    options:
      left: Left
      center: Center
      right: Right
    default: left

  ratio:
    width: 1/2
    label: Ratio
    type: select
    empty: false
    options:
      auto: Auto
      square: 1:1
      two-three: 2:3
      three-two: 3:2
      three-four: 3:4
      four-three: 4:3
      four-five: 4:5
      five-four: 5:4
      sixteen-nine: 16:9
    default: auto
    help: This sets the aspect ratio of your image or video. Select "Auto" to avoid cropping.

  include_max_width:
    width: 1/2
    label: Include Max Width?
    type: toggle
    text:
      - "no"
      - "yes"
    default: no

  max_width:
    width: 1/2
    label: Max Width
    type: range
    min: 25
    max: 100
    step: 1
    after: rem
    default: 50
    when:
      include_max_width: true