title: Header & Navigation

columns:
  nav_column_a:
    width: 1/2
    sections:
      nav_content:
        type: fields
        fields:

          nav_links_header:
            label: Navigation Content
            type: headline
            help: |
              Choose which pages to include in your site's navigation menu. Drag and drop to reorder the links in your navigation menu.
          
          nav_links:
            label: Add pages to the header navigation menu
            type: structure
            sortable: true
            fields:
              link:
                label: Page
                type: pages
                query: site.children.listed
                layout: list
                multiple: false
                link: false
              text:
                label: Link Text (optional)
                type: text
                placeholder: Leave this field blank to use the page title.
                empty: Leave this field blank to use the page title.
          
          nav_logo_header:
            label: Header Logo
            type: headline
            help: |
              Upload a logo to display in the header of your site.
          
          nav_logo:
            label: Add Logo
            type: files
            uploads:
              template: image--header-logo
            multiple: false
            layout: cardlets
            help : |
              Acceptable file types: **.png** and **.svg** (under 1MB). If you're using a .png file, make sure it has a _transparent background!_

          nav_help:
            label: SVG Hotline!
            type: info
            text: |
              **Always optimize your SVG using (link: https://svgomg.net/ text: SVGOMG target: _blank) prior to uploading.** Make sure you select the option _Prefer viewBox to width/height_ before exporting. Open the optimized SVG in a text editor and add **fill="currentColor"** inside the opening `<svg>` tag. The result will look something like this:
              
              `<svg viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg" fill="currentColor">`

              This will allow you to change the color of your logo using the **Logo Fill Color** field.

  nav_column_b:
    width: 1/2
    sections:
      nav_styles:
        type: fields
        fields:
          
          nav_styles_header:
            label: Header / Navigation Styles
            type: headline
            help: |
              Customize the appearance of your site's navigation menu.
          
          logo_fill_color:
            width: 1/2
            label: Logo Fill Color
            type: color
            alpha: true
            default: "Poppy"
            mode: options
            options:
              type: query
              query: kirby.option('brand.palette')
            help: Only applies to SVG logos. If you upload a PNG logo, the logo will be displayed as-is.

          menu_toggle_color:
            width: 1/2
            label: Menu Toggle Color
            type: color
            alpha: true
            default: "Asphalt"
            mode: options
            options:
              type: query
              query: kirby.option('brand.palette')
            help: Only applies to the mobile menu icon.

          nav_bg_color:
            width: 1/2
            label: Background Color
            type: color
            alpha: true
            default: "Drywall"
            mode: options
            options:
              type: query
              query: kirby.option('brand.palette')
          
          nav_fg_color:
            width: 1/2
            label: Text Color
            type: color
            alpha: true
            default: "Asphalt"
            mode: options
            options:
              type: query
              query: kirby.option('brand.palette')
          
          nav_font_size:
            width: 1/2
            label: Font Size
            type: number
            min: 0.5
            max: 3
            step: 0.125
            default: 1.5
            after: "rem"

          nav_height:
            width: 1/2
            label: Nav Bar Height
            type: number
            min: 2
            max: 10
            default: 4
            after: "rem"