title: Default Page

tabs:
  content:
    label: Page Content

    columns:
      main:
        width: 2/3
        sections:
          fields:
            type: fields
            fields:
              Blocks:
                type: blocks
                fieldsets:
                  hero:
                    label: Hero
                    type: group
                    fieldsets:
                      - hero
                      - split-hero
                  text:
                    label: Text
                    type: group
                    fieldsets:
                      - content
                      - accordions
                      - marquee
                  media:
                    label: Media
                    type: group
                    fieldsets:
                      - audio
                      - gallery
                      - image-slider
                      - media
                      - media-content

      sidebar:
        width: 1/3
        sections:
          # pages:
          #   type: pages
          #   template: default
          files:
            type: files

  seo:
    label: SEO Tools
    extends: tabs/page-seo