title: Default Page

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          Blocks:
            type: blocks
            fieldsets:
              - heading
              - text
              - image
              - accordions
              - audio
              - column_content

  sidebar:
    width: 1/3
    sections:
      pages:
        type: pages
        template: default
      files:
        type: files

