title: Default Page

tabs:
  content:
    label: Page Content

    columns:
      main:
        width: 2/3
        sections:
          fields:
            type: fields
            fields:
              Blocks:
                type: blocks
                fieldsets:
                  - heading
                  - text
                  - image
                  - accordions
                  - audio

      sidebar:
        width: 1/3
        sections:
          pages:
            type: pages
            template: default
          files:
            type: files

  seo:
    label: SEO Tools
    extends: tabs/page-seo