title: Site

tabs:
  dashboard:
    label: Dashboard
    sections:
      pages:
        type: pages
        layout: cards
        image:
          ratio: 5/4
          cover: true

  global-settings:
    label: Global Settings
    extends: tabs/global-settings

  company-information:
    label: Company Information
    extends: tabs/company-settings