title: Site

tabs:
  dashboard:
    label: Dashboard
    sections:
      pages:
        type: pages
        layout: cards
        image:
          ratio: 5/4
          cover: true
          back: "#f9f9f9"
          icon: 🖼️

  global-settings:
    label: Global Settings
    extends: tabs/global-settings

  navigation-settings:
    label: Header & Navigation
    extends: tabs/navigation-settings

  company-information:
    label: Company Information
    extends: tabs/company-settings